In [6]:
import numpy as np

In [7]:
vect = np.array([1,2,3])
vect.ndim #количество осей

1

In [8]:
mat = np.array([[1,2,3], [4,5,6]])
mat.ndim

2

In [9]:
vect.shape

(3,)

In [10]:
mat.dtype.name

'int64'

In [11]:
mat.itemsize

8

# Создание массивов
* ### передача итерируемого объекта в качестве параметра array

In [12]:
A = np.array([1,2,3])
A

array([1, 2, 3])

In [13]:
A = np.array([1,2,3], dtype = float)
A

array([1., 2., 3.])

In [14]:
B = np.array([(1,2,3), (2,3,4)])
B

array([[1, 2, 3],
       [2, 3, 4]])

* ### Создание массива специального вида zeros, ones, empty, identity

In [15]:
np.zeros((3,))

array([0., 0., 0.])

In [16]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
np.empty((3, 5))

array([[4.69036367e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000]])

* ### создание последовательностей с arange и linspace

In [19]:
np.arange(2, 20, 3)

array([ 2,  5,  8, 11, 14, 17])

In [20]:
np.arange(2.5, 8.8, 0.4)

array([2.5, 2.9, 3.3, 3.7, 4.1, 4.5, 4.9, 5.3, 5.7, 6.1, 6.5, 6.9, 7.3,
       7.7, 8.1, 8.5])

In [21]:
np.linspace(3, 8, 20)

array([3.        , 3.26315789, 3.52631579, 3.78947368, 4.05263158,
       4.31578947, 4.57894737, 4.84210526, 5.10526316, 5.36842105,
       5.63157895, 5.89473684, 6.15789474, 6.42105263, 6.68421053,
       6.94736842, 7.21052632, 7.47368421, 7.73684211, 8.        ])

* ### изменение размера массива с reshape

In [22]:
np.arange(12).reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
np.arange(10).reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

* ### транспонирование массива

In [24]:
C = np.arange(10).reshape(2, -1)
C

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [25]:
C.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

* ### объединение по оси

In [26]:
A = np.arange(6).reshape(2, -1)
np.hstack((A, A**2))

array([[ 0,  1,  2,  0,  1,  4],
       [ 3,  4,  5,  9, 16, 25]])

In [27]:
np.vstack((A, A**2))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 0,  1,  4],
       [ 9, 16, 25]])

In [28]:
np.concatenate((A, A**2), axis = 1)

array([[ 0,  1,  2,  0,  1,  4],
       [ 3,  4,  5,  9, 16, 25]])

* ### повторение существующего массива

In [29]:
a = np.arange(3)
np.tile(a, (2,3))

array([[0, 1, 2, 0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2, 0, 1, 2]])

In [30]:
np.tile(a, (4, 1))

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

# Базовые операции
* ### поэлементное выполнение операций

In [31]:
A = np.arange(9).reshape(3, 3)
B = np.arange(1, 10).reshape(3,3)

In [32]:
print(A)
print(B)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
A + B

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [34]:
A * 1 / B

array([[0.        , 0.5       , 0.66666667],
       [0.75      , 0.8       , 0.83333333],
       [0.85714286, 0.875     , 0.88888889]])

In [35]:
A + 1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
3*A

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [37]:
A ** 2

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

* ### умножение тоже является поэлементной операцией, а не матричной

In [38]:
A * B

array([[ 0,  2,  6],
       [12, 20, 30],
       [42, 56, 72]])

In [39]:
A.dot(B)

array([[ 18,  21,  24],
       [ 54,  66,  78],
       [ 90, 111, 132]])

* ### массивы могут быть преобразованы для выполнения поэлементных операций (broadcasting)

In [40]:
np.tile(np.arange(0, 40, 10), (3, 1)).T + np.array([0, 1, 2])

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [41]:
np.exp(A)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00],
       [2.00855369e+01, 5.45981500e+01, 1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03]])

* ### некоторым операциям можно задать ось выполнения

In [42]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [43]:
A.min()

0

In [44]:
A.max(axis = 0)

array([6, 7, 8])

In [45]:
A.sum(axis = 1)

array([ 3, 12, 21])

# Индексация

In [46]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
a[2:5]

array([2, 3, 4])

In [48]:
a[3:8:2]

array([3, 5, 7])

In [49]:
A = np.arange(81).reshape(9, -1)
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [50]:
A[2:4]

array([[18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [51]:
A[:, 2:4]

array([[ 2,  3],
       [11, 12],
       [20, 21],
       [29, 30],
       [38, 39],
       [47, 48],
       [56, 57],
       [65, 66],
       [74, 75]])

In [52]:
A[2:4, 2:4]

array([[20, 21],
       [29, 30]])

In [53]:
A[-1]

array([72, 73, 74, 75, 76, 77, 78, 79, 80])

* ### Индексация при помощи списков индексов

In [54]:
A = np.arange(81).reshape(9, -1)
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [55]:
A[[2,4, 5], [0, 1,3]]

array([18, 37, 48])

* ### применение логической индексации

In [56]:
A = np.arange(11)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
A[A % 5 != 3]

array([ 0,  1,  2,  4,  5,  6,  7,  9, 10])

In [58]:
A[np.logical_and(A!= 7, A % 5 != 3)]

array([ 0,  1,  2,  4,  5,  6,  9, 10])

# Оценка скорости работы numpy

In [59]:
import time

A_quick_arr = np.random.normal(size = (1000000,))
B_quick_arr = np.random.normal(size = (1000000,))

A_slow_list, B_slow_list = list(A_quick_arr), list(B_quick_arr)

In [60]:
start = time.process_time()
ans = 0
for i in range(len(A_slow_list)):
    ans += A_slow_list[i] * B_slow_list[i]
print(time.process_time() - start)

0.1870113899999999


In [61]:
start = time.process_time()
ans = sum([A_slow_list[i] * B_slow_list[i] for i in range(1000000)])
print(time.process_time() - start)

0.15062714499999985


In [62]:
start = time.process_time()
ans = np.sum(A_quick_arr * B_quick_arr)
print(time.process_time() - start)

0.003286850999999924


In [63]:
start = time.process_time()
ans = A_quick_arr.dot(B_quick_arr)
print(time.process_time() - start)

0.0012491720000000761


# Series

In [64]:
import pandas as pd
my_series = pd.Series([5, 6, 7, 8, 9, 10])
my_series

0     5
1     6
2     7
3     8
4     9
5    10
dtype: int64

In [65]:
my_series.index

RangeIndex(start=0, stop=6, step=1)

In [66]:
my_series.values

array([ 5,  6,  7,  8,  9, 10])

In [67]:
my_series[4]

9

In [68]:
my_series2 = pd.Series([5, 6, 7, 8, 9, 10], index = ['a', 'b', 'c', 'd', 'e', 'f'])
my_series2['f']

10

In [69]:
my_series2[['a', 'b', 'f']]

a     5
b     6
f    10
dtype: int64

In [70]:
my_series2[['a', 'b', 'f']] = 0
my_series2

a    0
b    0
c    7
d    8
e    9
f    0
dtype: int64

In [71]:
my_series2[my_series2 > 0]

c    7
d    8
e    9
dtype: int64

In [72]:
my_series2[my_series2 > 0] * 2

c    14
d    16
e    18
dtype: int64

In [73]:
my_series3 = pd.Series({'a': 5, 'b':6, 'c': 7, 'd': 8})
my_series3

a    5
b    6
c    7
d    8
dtype: int64

In [74]:
my_series3.index = ['A', 'B', 'C', 'D']
my_series3

A    5
B    6
C    7
D    8
dtype: int64

# DataFrame

In [75]:
df = pd.DataFrame({
    'country': ['Kazakhstan', 'Russia', 'Belarus', 'Ukraine'],
    'population': [17.04, 143.5, 9.5, 45.5],
    'square': [2724902, 17125191, 207600, 603628]
})
df

country  population    square
0  Kazakhstan       17.04   2724902
1      Russia      143.50  17125191
2     Belarus        9.50    207600
3     Ukraine       45.50    603628

In [76]:
df['country']

0    Kazakhstan
1        Russia
2       Belarus
3       Ukraine
Name: country, dtype: object

In [77]:
df.columns

Index(['country', 'population', 'square'], dtype='object')

In [78]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [79]:
df = pd.DataFrame({
    'country': ['Kazakhstan', 'Russia', 'Belarus', 'Ukraine'],
    'population': [17.04, 143.5, 9.5, 45.5],
    'square': [2724902, 17125191, 207600, 603628]
}, index = ['KZ', 'RU', 'BY', 'UA'])
df

country  population    square
KZ  Kazakhstan       17.04   2724902
RU      Russia      143.50  17125191
BY     Belarus        9.50    207600
UA     Ukraine       45.50    603628

In [80]:
df.index = ['KZ', 'RU', 'BY', 'UA']
df.index.name = 'Country Code'
df

country  population    square
Country Code                                  
KZ            Kazakhstan       17.04   2724902
RU                Russia      143.50  17125191
BY               Belarus        9.50    207600
UA               Ukraine       45.50    603628

In [81]:
df['country']

Country Code
KZ    Kazakhstan
RU        Russia
BY       Belarus
UA       Ukraine
Name: country, dtype: object

In [82]:
df.loc['KZ']

country       Kazakhstan
population         17.04
square           2724902
Name: KZ, dtype: object

In [83]:
df.iloc[0]

country       Kazakhstan
population         17.04
square           2724902
Name: KZ, dtype: object

In [84]:
df.iloc[2]

country       Belarus
population        9.5
square         207600
Name: BY, dtype: object

In [85]:
df.loc[['KZ', 'RU'], 'population']

Country Code
KZ     17.04
RU    143.50
Name: population, dtype: float64

In [86]:
df.loc['KZ':'BY', :]

country  population    square
Country Code                                  
KZ            Kazakhstan       17.04   2724902
RU                Russia      143.50  17125191
BY               Belarus        9.50    207600

In [87]:
df[df.population > 10][['country', 'square']]

country    square
Country Code                      
KZ            Kazakhstan   2724902
RU                Russia  17125191
UA               Ukraine    603628

In [88]:
df.reset_index()

Country Code     country  population    square
0           KZ  Kazakhstan       17.04   2724902
1           RU      Russia      143.50  17125191
2           BY     Belarus        9.50    207600
3           UA     Ukraine       45.50    603628

In [89]:
df['density'] = df['population'] / df['square'] * 1000000
df

country  population    square    density
Country Code                                             
KZ            Kazakhstan       17.04   2724902   6.253436
RU                Russia      143.50  17125191   8.379469
BY               Belarus        9.50    207600  45.761079
UA               Ukraine       45.50    603628  75.377550

In [90]:
df.drop(['density'], axis='columns')

country  population    square
Country Code                                  
KZ            Kazakhstan       17.04   2724902
RU                Russia      143.50  17125191
BY               Belarus        9.50    207600
UA               Ukraine       45.50    603628

In [91]:
df = df.rename(columns= {'Country Code': 'country_code'})
df

country  population    square    density
Country Code                                             
KZ            Kazakhstan       17.04   2724902   6.253436
RU                Russia      143.50  17125191   8.379469
BY               Belarus        9.50    207600  45.761079
UA               Ukraine       45.50    603628  75.377550

In [92]:
titanick_df = pd.read_csv('titanic.csv')
print(titanick_df.head())

ParserError: Error tokenizing data. C error: Expected 4 fields in line 3, saw 6
